### ISSUE TITLE
Collect suggestions for Soul renamed

### ISSUE THREAD

**Issue by yu199195** [dromara/shenyu#1215]
Hi All guys:

soul will be rename, Could you do me a small favor?  

The name rules are as follows :

* The name is easy to understand

* It is best to have a name with the meaning of gateway such as bridge, proxy, governance

* The name cannot be the same as the existing project name

* Don't use your name for other trademarks

thanks ALL

**Comment by shimingxy** [comment]
dromara gateway

**Comment by yezj0010** [comment]
stargate

**Comment by qiuchen100** [comment]
FlashDog

**Comment by shimingxy** [comment]
https://github.com/stargate/stargate used

**Comment by zendwang** [comment]
stone lion :  watch internet entrance of enterprise

**Comment by JohnChen92** [comment]
Cateway : Change the initial of gateway to ‘ C ’ 
cat and cate。

**Comment by sunl888** [comment]
Balan:  balance gateway

**Comment by JohnChen92** [comment]
Cateway : Change the “G” of gateway to “C”
cat and cate

**Comment by Wincher** [comment]
Qiao which means Pinyin of Chinese 桥 没错就是这么直白

**Comment by onlyonezhongjinhui** [comment]
sky Road

**Comment by onlyonezhongjinhui** [comment]
Soul guard

**Comment by wyc192273** [comment]
soulone: 
soul backbone 灵魂支柱
Soulow: 
Soul Flow 灵魂心流

**Comment by kminjava** [comment]
SoulWay

**Comment by Zhoutzzz** [comment]
miracle gateway

**Comment by kminjava** [comment]
SoulWay

**Comment by xiaoshen11** [comment]
atman-gateway  灵魂网关（atman 来自古印度梵文，灵魂的意思。-》soul）

**Comment by ooooo-youwillsee** [comment]
lwy

**Comment by zhangminpeng** [comment]
ferry-way

**Comment by jmwasky** [comment]
Being Gateway

**Comment by babynata** [comment]
Pudding

**Comment by tuohai666** [comment]
Asgard


```
Asgard (Old Norse: Ásgarðr; “Enclosure of the Aesir”) is a location associated with gods.
```

![image](https://user-images.githubusercontent.com/24643893/113375221-85e00180-93a1-11eb-9517-0f519c3082e3.png)


There are natural nexus **portals** that exist on Asgard, due to deposits of the wormhole-sensitive, crystal-like material used in the construction of the Bifrost Bridge. These portals are in direct **contact** with the roots of Yggdrasil, a tree-like **cosmic grid** that **connects** the Nine Realms. Heimdall **operates** and **safeguards** the Bifrost Bridge from Himinbjorg. The Asgardian **government** operates through a strict monarchy which separates the royal family from regular Asgardians.[2]


Another notable feature in Asgard is the Bifrost **Bridge**, which provides **passage** to all the Nine Realms, but can only be opened if **permitted** by its guardian, Heimdall.

**Comment by strawberry-crisis** [comment]
Yu 
name for "大禹"

**Comment by zhangcly** [comment]
NetBrain haha

**Comment by tuohai666** [comment]
Arda

Arda (Quenya; IPA: [ˈarda] – Realm), also known as Earth, was the world in which all peoples of Middle-earth and of Valinor lived.

The world in `The Lord of the Rings`。

**Comment by tuohai666** [comment]
GoldenWay

**Comment by tuohai666** [comment]
GreateYu

**Comment by tuohai666** [comment]
Kunlun

**Comment by tuohai666** [comment]
MilkyWay 

天河（银河）

**Comment by tuohai666** [comment]
Lynx
pronounce /lɪŋks/, same as Links

![image](https://user-images.githubusercontent.com/24643893/113656708-0159ef80-96cf-11eb-9662-7b429eed272f.png)

**Comment by panyox** [comment]
## Torana

> Torana, also referred to as vandanamalikas, is a free-standing ornamental or arched gateway for ceremonial purposes seen in the Hindu, Buddhist and Jain architecture of the Indian subcontinent, Southeast Asia and parts of East Asia. Chinese paifang gateways, Japanese torii gateways,Korean Hongsalmun gateways, and Thai Sao Ching Cha were derived from the Indian torana.
>
by Wiki

**Comment by tuohai666** [comment]
DayuSoul

**Comment by tuohai666** [comment]
DayuWay

**Comment by tuohai666** [comment]
DayuGate

**Comment by tuohai666** [comment]
DayuGateway

**Comment by tuohai666** [comment]
DaYuZhiShui

**Comment by tuohai666** [comment]
DayuX

**Comment by tuohai666** [comment]
DayuKing

**Comment by tuohai666** [comment]
YuKing

**Comment by tuohai666** [comment]
DiYu

**Comment by tuohai666** [comment]
ShenYu

**Comment by tuohai666** [comment]
KingYu

**Comment by tuohai666** [comment]
Getway

**Comment by dmsolr** [comment]
Shiper(Scalable HIgh-PErformance Responsive) API Gateway

**Comment by tuohai666** [comment]
Aratar

**Comment by tuohai666** [comment]
YaoShunYu

**Comment by tuohai666** [comment]
Ancient One

**Comment by tuohai666** [comment]
Nenya

**Comment by tuohai666** [comment]
calaquendi

**Comment by tuohai666** [comment]
Lar 

古罗马人们相信拉尔可以保护和影响其领地内所发生的一切

**Comment by qiuchen100** [comment]
@tuohai666 不要老发了，发发发！！！ 你还发个锤子啊

**Comment by qiuchen100** [comment]
@tuohai666 不要老发，发发发！！ 发个锤子啊！！~

**Comment by BrightLoong** [comment]
Bifrost

**Comment by yu199195** [comment]
@BrightLoong  already exist
