### ISSUE TITLE
2.3.0 soul admin java.lang.ClassCastException bug

### ISSUE THREAD

**Issue by Origin-zhao** [dromara/shenyu#1231]
## Describe the bug
in 2.3.0 admin soul , when MetaData be push, have a  java.lang.ClassCastException: org.dromara.soul.admin.entity.MetaDataDO cannot be cast to org.dromara.soul.common.dto.MetaData

## Environment

- Soul version(s): [e.g. 2.3.0]

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by dengliming** [comment]
Can you provide the steps to reproduce this issue? and PR is welcome : )

**Comment by zhangjh** [comment]
I met this error too,I'll submit a pr, plz review

**Comment by yu199195** [comment]
Hi  zhangjh

what error ?
