### ISSUE TITLE
if querString include chinese  route path will be UrlEncode

### ISSUE THREAD

**Issue by linchuyao** [dromara/shenyu#1289]
soul version 2.3.0
<img width="773" alt="BE313F91-927D-4458-8394-11FFD5B45AD3" src="https://user-images.githubusercontent.com/32710423/115489414-bcb58300-a28e-11eb-9bb9-5ce9af6f9384.png">
![C5169071-56A0-4C58-8681-EA2A13012E29](https://user-images.githubusercontent.com/32710423/115489436-c3dc9100-a28e-11eb-9484-ff2e5b61148b.png)

**Comment by yu199195** [comment]
will be fix in the next version

**Comment by leohou0430** [comment]
1. in DividePlugin, the buildRealURL method get request query is by `exchange.getRequest().getURI().getRawQuery()`
2. when use postman send request ,can close auto encoding 
![image](https://user-images.githubusercontent.com/3467826/115676874-953fe280-a382-11eb-95a3-ec765fb836e3.png)

**Comment by linchuyao** [comment]
> 1. in DividePlugin, the buildRealURL method get request query is by `exchange.getRequest().getURI().getRawQuery()`
> 2. when use postman send request ,can close auto encoding
>    ![image](https://user-images.githubusercontent.com/3467826/115676874-953fe280-a382-11eb-95a3-ec765fb836e3.png)

This question has nothing to do with postman

**Comment by yu199195** [comment]
Hi, fix it in master, i will close this issue..
