### ISSUE TITLE
PluginHandle configuration not work

### ISSUE THREAD

**Issue by PandaUncle** [dromara/shenyu#1294]
## Describe the bug
Configure PluginHandle .
PluginName: divide
FieldName: timeout
DefaultValue: 10000
I hope when rule registered，the timeout is 10000,  but still 3000.

In the plugin processing management, configure the timeout of the divide plugin to 10000 (the system default is 3000). After the rule is registered, the timeout of the rule is still 3000. I originally hoped that the registered rules could be 10000 in accordance with the configuration timeout in the processing management

## Environment

- Soul version(s): 2.3.0

**Comment by zendwang** [comment]
I will follow up this question.keep contact!

**Comment by zendwang** [comment]
we will fix it on next version.

**Comment by nuo-promise** [comment]
The current version of the interface registration does not go to the pluginhandle table to read the plugin attribute value. Under our internal evaluation, this function will be added if necessary.

**Comment by nuo-promise** [comment]
Need to be optimized? @yu199195 @dengliming

**Comment by nuo-promise** [comment]
After discussion, support is not considered for the time being, and the issue will be closed in one day.
