### ISSUE TITLE
In the meta data form, the path description field is not required, but in the database table , the path_desc field is not null.

### ISSUE THREAD

**Issue by PandaUncle** [dromara/shenyu#1363]
## Describe the bug
In the meta data form, the path description field is not required, but in the database table , the path_desc field is not null.
if not input path description, an error will throw, when saving.

**Comment by yu199195** [comment]
maybe refactor sql， set is null

**Comment by qurenneng** [comment]
I've come to

**Comment by PandaUncle** [comment]
I am working on it, I will finish it today.

**Comment by yu199195** [comment]
the Solution 

1. refactor sql in schema.sql and schema.h2.sql
2.  create soul_2.4.0.sql file in soul/script  (alert  sql  to fix it)

**Comment by PandaUncle** [comment]
To avoid adding upgrade scripts, i will give it a empty string value when "pathDesc" is null.
