### ISSUE TITLE
Suggestions for improvements to the Apache dubbo plugin

### ISSUE THREAD

**Issue by dengliming** [dromara/shenyu#1381]
1、https://github.com/dromara/soul/blob/54281b06669c74fb994a72e0e71474c4b5030399/soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/cache/ApplicationConfigCache.java#L157

`ApplicationModel.getConfigManager().` only support in `2.7.5+`, If we need to be compatible with lower versions, we should use 
`reference.setApplication(applicationConfig);`

2、Avoid always using reflection to get the invoke URL. (Maybe cache it would be better)
https://github.com/dromara/soul/blob/54281b06669c74fb994a72e0e71474c4b5030399/soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java#L112

**Comment by tydhot** [comment]
I'll see later

**Comment by ttttangzhen** [comment]
If it's possible, I want to try to fix this problem


> I'll see later

**Comment by tydhot** [comment]
> If it's possible, I want to try to fix this problem
> 
> > I'll see later

fine, you can think about how to optimize the no.2 question
