### ISSUE TITLE
Integrated SkyWalking

### ISSUE THREAD

**Issue by Trafalgar-YuI** [dromara/shenyu#1395]
## Task

1. I will create discuss group
2. Everyone try to use SkyWalking
3. Discuss the plan how to integrated
4. Division of labor
5. Coding

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

If you want to participate, please reply this issue.

**Comment by zenglinhui** [comment]
get

**Comment by Wincher** [comment]
I want to get part in this

**Comment by ttttangzhen** [comment]
I want to join you

**Comment by zhaiweij** [comment]
thank you,I want to participate in discussions

**Comment by hubao-1125** [comment]
get

**Comment by bird-man04** [comment]
I want to make something for this

**Comment by HugogoChan** [comment]
I want to make it with you

**Comment by Trafalgar-YuI** [comment]
> I want to make something for this

how can I contact you.

**Comment by Trafalgar-YuI** [comment]
@bird-man04 How can I contact you

**Comment by WYUSIG** [comment]
I want to make something for this

**Comment by bird-man04** [comment]
> @bird-man04 How can I contact you

My wx Id is fengshengyao04
