### ISSUE TITLE
ShenYu Logo design!

### ISSUE THREAD

**Issue by yu199195** [dromara/shenyu#1400]
Hi, community

We need to design the logo of Shenyu.  Please provide your ideas for this logo 

if you want, Reply below this issue.

**Comment by Asxing** [comment]
![image](https://user-images.githubusercontent.com/22816271/117921685-be211b00-b323-11eb-97a2-b71d6e775d68.png)

**Comment by Asxing** [comment]
![image](https://user-images.githubusercontent.com/22816271/117921714-cbd6a080-b323-11eb-8875-cd61f39c1b2d.png)

![image](https://user-images.githubusercontent.com/22816271/117921719-ce38fa80-b323-11eb-9ce5-4b24076abad9.png)

**Comment by Asxing** [comment]
![image](https://user-images.githubusercontent.com/22816271/117921806-f88ab800-b323-11eb-8382-119233084f9a.png)

**Comment by Asxing** [comment]
![Uploading image.png…]()

**Comment by Asxing** [comment]
![image](https://user-images.githubusercontent.com/22816271/117921858-0dffe200-b324-11eb-8b13-6dcda77af1ab.png)

**Comment by Asxing** [comment]
![image](https://user-images.githubusercontent.com/22816271/117921922-2a9c1a00-b324-11eb-9015-f501a13b944d.png)

**Comment by Asxing** [comment]
![image](https://user-images.githubusercontent.com/22816271/117922024-5c14e580-b324-11eb-8475-d4301436a085.png)

**Comment by Asxing** [comment]
![image](https://user-images.githubusercontent.com/22816271/117922051-6d5df200-b324-11eb-9a60-4bbc61c39e5e.png)

**Comment by Asxing** [comment]
![image](https://user-images.githubusercontent.com/22816271/117922117-8e264780-b324-11eb-8bd8-87e17f78f88b.png)

**Comment by Asxing** [comment]
![image](https://user-images.githubusercontent.com/22816271/117922143-9b433680-b324-11eb-9cc1-c0c73ef0348c.png)

**Comment by Asxing** [comment]
![image](https://user-images.githubusercontent.com/22816271/117922233-bb72f580-b324-11eb-9088-b1638a4f67e9.png)

**Comment by Asxing** [comment]
![image](https://user-images.githubusercontent.com/22816271/117922448-0db41680-b325-11eb-86b6-c7733a09abe1.png)

**Comment by Asxing** [comment]
![image](https://user-images.githubusercontent.com/22816271/117922825-a0ed4c00-b325-11eb-8eb4-ca861949f482.png)


![image](https://user-images.githubusercontent.com/22816271/117922969-dc881600-b325-11eb-8569-e80ed30e8800.png)

**Comment by kimmking** [comment]
![image](https://user-images.githubusercontent.com/807508/118488476-59642700-b74e-11eb-9495-037624deb9da.png)

this logo is designed with powerpoint with the zip file.
you can try it yourself and upload here.
[shenyu-logo.pptx.zip](https://github.com/dromara/shenyu/files/6493734/shenyu-logo.pptx.zip)

**Comment by jmwasky** [comment]
![shenyu](https://user-images.githubusercontent.com/3257442/119930144-794ae480-bfb1-11eb-9dc2-ed65b66a0343.png)
