### ISSUE TITLE
For soul rename to shenyu modify file readme.md

### ISSUE THREAD

**Issue by hubao-1125** [dromara/shenyu#1407]
## Task

A clear and concise description of Task

Task List:

- [ modify file readme.md ] task1

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by dengliming** [comment]
Resolved by [https://github.com/dromara/shenyu/pull/1408](https://github.com/dromara/shenyu/pull/1408) and thanks to @hubao-1125
