### ISSUE TITLE
 When creating metadata, generate the corresponding rule in the plugin

### ISSUE THREAD

**Issue by ttttangzhen** [dromara/shenyu#1411]
Now users need to configure metadata and then configure rules to use the dubbo plugin.

Shenyu can provide the option of whether to create corresponding rules at the same time.

for example, if users create dubbo metadata and choose generate rule, show users the dubbo selectors to choose. 
and then generate the corresponding rule in this selector.

**Comment by KevinClair** [comment]
I have a question, Why create a selector before uploading metadata?

**Comment by ttttangzhen** [comment]
> I have a question, Why create a selector before uploading metadata?

there is no strict order when creating them. 

shenyu use uri to choose metadata, rule filter use uri to filter requests. In fact, metadata has the same status as rules.

This feature is only an option, it's a supplement to dubbo client. 
For some third-party interfaces, users can't use the dubbo client, and can use this method to improve efficiency

**Comment by ttttangzhen** [comment]
> If they can't use `dubbo client`, they should create the metedata, selector and rules. Choose the selector if it has been existed, and add the rule after the selector.

Do you mean metadata must be created before selector?
If not, My idea might improve efficiency. 
I think metadata and selector are not created in a strict order.

**Comment by KevinClair** [comment]
That's not what I mean.

**Comment by ttttangzhen** [comment]
> That's not what I mean.

😀 明杰兄，我目前使用的时候，面对大量的接口，每个都要去创建metadata，然后把创建rule元数据放到selector中，这个过程可以由shenyu自动完成吧。
