### ISSUE TITLE
Diagrams

### ISSUE THREAD

**Issue by xyz-mtl** [dromara/shenyu#1418]
## Question

Your diagram is very clean

https://camo.githubusercontent.com/1f13bcef0a74d0eb5d4dcfef173967bafb31e0276f1ddfe5b9765307a863cf19/68747470733a2f2f64726f6d6172612e6f72672f696d672f736f756c2f61637469766974652f736f756c2d786d696e642e706e67

What is the tool used for this brainstorming?

Thanks

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by lw1243925457** [comment]
It maybe use xmind: https://www.xmind.net/xmind8-pro/

**Comment by xyz-mtl** [comment]
Thank you
