### ISSUE TITLE
Discuss about initial PPMC

### ISSUE THREAD

**Issue by yu199195** [dromara/shenyu#1425]
Hi, community 

We need to make sure PPMC To help us develop better at Apache Incubator

Now , I propose the following rules：

Code for ShenYu

1. committers and add code top 10 and code has been submitted in the half a year

code for shenyu-dashboard

1. committers and add code top 3 and code has been submitted in the half a year

community:

1.Actively running the community as a mentor （mentor ： Meetup organizers or Community keynote speaker）
2.Answering community questions

So result PPMC list is  :

shenyu (github-id) :

yu199195
dengliming
tydot
Asxing
nuo-promise
SaberSola
lw1243925457

shenyu-dashboard (github-id):
fengzhenbing

community(github-id) :

kimmking: as Apache Dubbo & ShardingSphere PMC member, he organizes source sharing activities, bringing important help to the community.
tuohai666 : as Apache ShardingSphere PMC member, he is actively involved in community discussions and activities, and give powerful help about the community conform to Apache Way.

Finally
Above is just my suggestion, welcome anybody to discuss together （Fair, just and open）.

Voters can either respond "agree, yes, +1", or "-1  Im not agree ".

**Comment by SaberSola** [comment]
agree

**Comment by lw1243925457** [comment]
agree

**Comment by SteNicholas** [comment]
+1

**Comment by fengzhenbing** [comment]
agree

**Comment by Trafalgar-YuI** [comment]
agree

**Comment by nuo-promise** [comment]
yes

**Comment by Asxing** [comment]
I couldn't agree more.

**Comment by Redick01** [comment]
agree

**Comment by dengliming** [comment]
+1

**Comment by kimmking** [comment]
+1 approval.

**Comment by songyuequan** [comment]
Of course I agree

**Comment by fightingting** [comment]
agree

**Comment by tydhot** [comment]
+1

**Comment by KevinClair** [comment]
+1

**Comment by 0x12FD16B** [comment]
agree

**Comment by tcray** [comment]
+1

**Comment by strawberry-crisis** [comment]
agreed

**Comment by ChoviWu** [comment]
agree

**Comment by MarcusJiang1306** [comment]
agree

**Comment by yu199195** [comment]
it pass, i will close it.
