### ISSUE TITLE
AlibabaDubboServiceBeanListener

### ISSUE THREAD

**Issue by JemyXiao** [dromara/shenyu#1439]
hi，
 branch: master
 class: AlibabaDubboServiceBeanListener
 method: onApplicationEvent
 env: springboot
detail: init AlibabaDubboServiceBeanListener invoke onApplicationEvent
Map<String, ServiceBean> serviceBean = contextRefreshedEvent.getApplicationContext().getBeansOfType(ServiceBean.class); 
serviceBean.size() = 0

**Comment by yu199195** [comment]
whats the dubbo version?  you use XML config or spring boot starter?

**Comment by JemyXiao** [comment]
> whats the dubbo version? you use XML config or spring boot starter?

dubbo version is 2.6.0
i use springboot starter ver=2.0.0

**Comment by KevinClair** [comment]
Please show us your `dubbo service interface`

**Comment by JemyXiao** [comment]
> Please show us your `dubbo service interface`
![image](https://user-images.githubusercontent.com/11550454/117926008-a9945100-b32a-11eb-8fd3-a309014e7a04.png)

**Comment by KevinClair** [comment]
May be you have to make sure that your dubbo service has been upload the register address.

**Comment by yu199195** [comment]
@KevinClair  i think it the dubbo-spring-boot-starter , not register spring bean,  can you fix it？

**Comment by JemyXiao** [comment]
> May be you have to make sure that your dubbo service has been registed successfully.

i am sure dubbo service registed successful already.

**Comment by KevinClair** [comment]
> @KevinClair i think it the dubbo-spring-boot-starter , not register spring bean, can you fix it？

ok. i will fix it.

**Comment by JemyXiao** [comment]
@KevinClair i find another problem, i try registry ServiceBean successful,but when invoke AlibabaDubboServiceBeanListener
handler method,line 101 method.getAnnotation(ShenyuDubboCilent.Class) is null.
please look it together,thanks.

**Comment by KevinClair** [comment]
> @KevinClair i find another problem, i try registry ServiceBean successful,but when invoke AlibabaDubboServiceBeanListener
> handler method,line 101 method.getAnnotation(ShenyuDubboCilent.Class) is null.
> please look it together,thanks.
> ![image](https://user-images.githubusercontent.com/11550454/117943876-2af5de80-b33f-11eb-9dfd-2a0c58a5ae75.png)

Got it.

**Comment by yu199195** [comment]
I think dubbo proxy bean maybe miss the anontation...

**Comment by JemyXiao** [comment]
> I think dubbo proxy bean maybe miss the annotation, if use dubbo annotation type..

i agree with you, i hope it can be fixed together?

**Comment by KevinClair** [comment]
Hello @JemyXiao ,I've tried many times and it's all successful.Here are some of my configuration.
* Maven dependency
```java
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>dubbo</artifactId>
    <version>2.6.0</version>
</dependency>

<dependency>
    <groupId>com.101tec</groupId>
    <artifactId>zkclient</artifactId>
    <version>0.10</version>
</dependency>

<dependency>
    <groupId>org.apache.shenyu</groupId>
    <artifactId>shenyu-spring-boot-starter-client-alibaba-dubbo</artifactId>
    <version>2.3.1-SNAPSHOT</version>
</dependency>
```
* spring-dubbo.xml file
```java
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://code.alibabatech.com/schema/dubbo"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       http://www.springframework.org/schema/beans/spring-beans.xsd
       http://code.alibabatech.com/schema/dubbo
       http://code.alibabatech.com/schema/dubbo/dubbo.xsd">

    <dubbo:application name="demo-service"/>
    <!-- 注册中心的ip地址 -->
    <dubbo:registry protocol="zookeeper" address="localhost:2181"/>
    <!-- 协议/端口-->
    <dubbo:protocol name="dubbo" port="20880"/>
    <!-- 暴露的接口 -->
    <dubbo:service ref="dubboService" interface="com.example.demo.dubbo.TestService"
                   timeout="3000" />
</beans>
```
* Service
```java
@Service("dubboService")
public class TestServiceImpl implements TestService {

    @Override
    @ShenyuDubboClient(path = "/test")
    public String test() {
        return "haha";
    }
}
```
* Configuration
```java
shenyu:
  client:
    registerType: http #zookeeper #etcd #nacos #consul
    serverLists: http://localhost:9095 #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      contextPath: /dubbo
      appName: dubbo
      nacosNameSpace: ShenyuRegisterCenter
      port: 20888
```

And when I run my application.
![微信截图_20210512172943](https://user-images.githubusercontent.com/37257651/117952758-094d2500-b348-11eb-8525-743a79ce64ba.png)
![微信截图_20210512173016](https://user-images.githubusercontent.com/37257651/117952789-110cc980-b348-11eb-85d9-5abac429ec51.png)

**Comment by yu199195** [comment]
@KevinClair  He not use XML， used Annotation.....

**Comment by KevinClair** [comment]
> @KevinClair He not use XML， used Annotation.....

Sorry, I run application with Annotation, It works as well.

**Comment by JemyXiao** [comment]
> > @KevinClair He not use XML， used Annotation.....
> 
> Sorry, I run application with Annotation, It works as well.

please show detail your dubbo service impl

**Comment by JemyXiao** [comment]
@KevinClair please remove dubbo config xml,retry add @Service dubbo Annotation

**Comment by JemyXiao** [comment]
![image](https://user-images.githubusercontent.com/11550454/118063559-ef552600-b3cb-11eb-97aa-5c4f9fb766a3.png)

**Comment by KevinClair** [comment]
> @KevinClair please remove dubbo config xml,retry add @service dubbo Annotation

I try it and works as well.
```java
import com.alibaba.dubbo.config.annotation.Service;
import com.example.demo.dubbo.TestService;
import org.apache.shenyu.client.dubbo.common.annotation.ShenyuDubboClient;
import org.springframework.stereotype.Component;

/**
 * Des
 *
 * @author kevin
 * @date 2021/5/12 16:57
 **/
@Component
@Service
public class TestServiceImpl implements TestService {

    @Override
    @ShenyuDubboClient(path = "/test")
    public String test() {
        return "haha";
    }
}
```

**Comment by yu199195** [comment]
@KevinClair  Hi, @Services is Dubbo Annotaion, not spring

**Comment by JemyXiao** [comment]
> > @KevinClair please remove dubbo config xml,retry add @service dubbo Annotation
> 
> I try it and works as well.
> 
> ```java
> import com.alibaba.dubbo.config.annotation.Service;
> import com.example.demo.dubbo.TestService;
> import org.apache.shenyu.client.dubbo.common.annotation.ShenyuDubboClient;
> import org.springframework.stereotype.Component;
> 
> /**
>  * Des
>  *
>  * @author kevin
>  * @date 2021/5/12 16:57
>  **/
> @Component
> @Service
> public class TestServiceImpl implements TestService {
> 
>     @Override
>     @ShenyuDubboClient(path = "/test")
>     public String test() {
>         return "haha";
>     }
> }
> ```

in think your xml not remove

**Comment by KevinClair** [comment]
> in think your xml not remove

I delete xml file.

**Comment by KevinClair** [comment]
Hello @JemyXiao , if you can, please send your simple example to my emil `kevinclair@apache.org` so that we can check the problem.

**Comment by JemyXiao** [comment]
> Hello @JemyXiao , if you can, please send your simple example to my emil `kevinclair@apache.org` so that we can check the problem.

i use shenyu-examples-alibaba-dubbo-service module, i edit DubboTestServiceImpl use dubbo @Service Annotation, u can try it

**Comment by JemyXiao** [comment]
> > Hello @JemyXiao , if you can, please send your simple example to my emil `kevinclair@apache.org` so that we can check the problem.
> 
> i use shenyu-examples-alibaba-dubbo-service module, i edit DubboTestServiceImpl use dubbo @service Annotation, u can try it

![image](https://user-images.githubusercontent.com/11550454/118073938-824b8b80-b3df-11eb-832a-6663c5d1804e.png)

**Comment by KevinClair** [comment]
Got it.

**Comment by KevinClair** [comment]
Hello @JemyXiao , I have found problem, you have to add `@DubboComponentScan({"org.apache.shenyu.examples.alibaba.dubbo.service.impl"})` in the `org.apache.shenyu.examples.alibaba.dubbo.service.TestAlibabaDubboApplication` to make sure Dubbo scan your interface with `@Service`, just like this:
* TestAlibabaDubboApplication
```java
@SpringBootApplication
@ImportResource({"classpath:spring-dubbo.xml"})
@DubboComponentScan({"org.apache.shenyu.examples.alibaba.dubbo.service.impl"})
public class TestAlibabaDubboApplication {

    /**
     * Main Entrance.
     *
     * @param args startup arguments
     */
    public static void main(final String[] args) {
        SpringApplication.run(TestAlibabaDubboApplication.class, args);
    }

}
```
* DubboTestServiceImpl 
```java
package org.apache.shenyu.examples.alibaba.dubbo.service.impl;

import java.util.Arrays;
import java.util.Random;

import com.alibaba.dubbo.config.annotation.Service;
import org.apache.shenyu.client.dubbo.common.annotation.ShenyuDubboClient;
import org.apache.shenyu.examples.dubbo.api.entity.DubboTest;
import org.apache.shenyu.examples.dubbo.api.entity.ListResp;
import org.apache.shenyu.examples.dubbo.api.service.DubboTestService;
import org.springframework.stereotype.Component;

/**
 * DubboTestServiceImpl.
 */
@Component("dubboTestService")
@Service
public class DubboTestServiceImpl implements DubboTestService {

@Override
    @ShenyuDubboClient(path = "/findById", desc = "Query by Id")
    public DubboTest findById(final String id) {
        DubboTest dubboTest = new DubboTest();
        dubboTest.setId(id);
        dubboTest.setName("hello world shenyu Alibaba Dubbo, findById");
        return dubboTest;
    }
}
```
* spring-dubbo.xml
```java
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://code.alibabatech.com/schema/dubbo"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       http://www.springframework.org/schema/beans/spring-beans.xsd
       http://code.alibabatech.com/schema/dubbo
       http://code.alibabatech.com/schema/dubbo/dubbo.xsd">

    <dubbo:application name="test-dubbo-service"/>

    <dubbo:registry address="zookeeper://localhost:2181"/>

    <dubbo:protocol name="dubbo" port="20888"/>

<!--    <dubbo:service timeout="10000" interface="org.apache.shenyu.examples.dubbo.api.service.DubboTestService" ref="dubboTestService"/>-->

<!--    <dubbo:service timeout="10000" interface="org.apache.shenyu.examples.dubbo.api.service.DubboMultiParamService" ref="dubboMultiParamService"/>-->
</beans>
```

* if you delete spring-dubbo.xml, you have to add configuration in the application.yml and add `@EnableDubbo` in `TestAlibabaDubboApplication`, for example:
```java
@SpringBootApplication
@EnableDubbo
public class TestAlibabaDubboApplication {

    /**
     * Main Entrance.
     *
     * @param args startup arguments
     */
    public static void main(final String[] args) {
        SpringApplication.run(TestAlibabaDubboApplication.class, args);
    }

}
```
```yml
dubbo:
  application:
    name: demo-service
  registry:
    protocol: zookeeper
    address: localhost:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: org.apache.shenyu.examples.alibaba.dubbo.service.impl
```

**Comment by JemyXiao** [comment]
@KevinClair thanks for patiently answer, i try it successfull follow your way.
about another problem not found @ShenyuXXXClient Annotation from impl class, i fix it and pull request also.

**Comment by KevinClair** [comment]
> @KevinClair thanks for patiently answer, i try it successfull follow your way.
> about another problem not found @ShenyuXXXClient Annotation from impl class, i fix it and pull request also.

But if you follow my way, `@ShenyuXXXClient` would be found.

**Comment by JemyXiao** [comment]
> > @KevinClair thanks for patiently answer, i try it successfull follow your way.
> > about another problem not found @ShenyuXXXClient Annotation from impl class, i fix it and pull request also.
> 
> But if you follow my way, `@ShenyuXXXClient` would be found.

The scene is like this，I run my project not shenyu-example,my impl class generate spring proxy, so when handler method AopUtils.isCglibProxy() param type has a problem, i had pr. please code review my pr code
