### ISSUE TITLE
buildparameter forget add paramNameList

### ISSUE THREAD

**Issue by Ting97** [dromara/shenyu#1451]
## Describe the bug

When the parameter is one and the type starts with “java”， 500 will be reported
![image](https://user-images.githubusercontent.com/48816907/118124448-2c4f0600-b428-11eb-95c7-f2bb00963fd7.png)

When i debug,  i find this medthod has problem
org.apache.shenyu.plugin.api.utils.BodyParamUtils#buildParameters 

we can see paramNameList.size() = 0, it cause param's value is null
![image](https://user-images.githubusercontent.com/48816907/118125541-b8156200-b429-11eb-9a12-2bed37a762c8.png)
![image](https://user-images.githubusercontent.com/48816907/118125775-fc086700-b429-11eb-9043-907537b5d838.png)

add some code in org.apache.shenyu.plugin.api.utils.BodyParamUtils#buildParameters  can fix it

![image](https://user-images.githubusercontent.com/48816907/118126358-cb74fd00-b42a-11eb-827f-515eeb393d48.png)

**Comment by ttttangzhen** [comment]
Thanks for reporting this
Can you fix it? Or I will fix it in the upcoming pr

**Comment by Ting97** [comment]
> Thanks for reporting this
> Can you fix it? Or I will fix it in the upcoming pr

I can fix it today, and I will pr, ok?

**Comment by ttttangzhen** [comment]
> > Thanks for reporting this
> > Can you fix it? Or I will fix it in the upcoming pr
> 
> I can fix it today, and I will pr, ok?

Ok 😁
