### ISSUE TITLE
start.sh script problem

### ISSUE THREAD

**Issue by kenWu-github** [dromara/shenyu#1473]
## Describe the bug

JAVA_OPTS does not take effect in the start.sh script

## Environment

- Soul version(s): 2.3.2-SNAPSHOT

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by dengliming** [comment]
we already resolved it by [https://github.com/dromara/shenyu/pull/1468](https://github.com/dromara/shenyu/pull/1468)
