### ISSUE TITLE
 There may be a wrong way to use guava cache

### ISSUE THREAD

**Issue by ttttangzhen** [dromara/shenyu#1477]
in `org.apache.shenyu.plugin.apache.dubbo.cache.ApplicationConfigCache` and ApplicationConfigCache in other RPC plugin

```
private final LoadingCache<String, ReferenceConfig<GenericService>> cache = CacheBuilder.newBuilder()
            .maximumWeight(maxCount)
            .weigher((Weigher<String, ReferenceConfig<GenericService>>) (string, referenceConfig) -> getSize())
            .removalListener(notification -> {
                // ignore...
            })
            .build(new CacheLoader<String, ReferenceConfig<GenericService>>() {
                // ignore...
            });

private int getSize() {
    return (int) cache.size();
}
```

Here, weight is used to control the total capacity of `guava cache`, but the weight of each cache use `getSize`,it represents the total number of items cached when a piece of data is cached.

I think there may be wrong usage here, If we use weights, the weights should represent the size of each piece of data
, so here should be replaced by the number of bars to control the total capacity

**Comment by ben-manes** [comment]
That does sound like a bug to me, too. You should also be aware that, in Guava, the maximum weight of a single entry is `maximumWeight / concurrnecyLevel`, where `concurrnecyLevel` is by default 4. This is because the cache is broken into independent sub-caches (segments). In this configuration, when the cache is full then the new entry will be immediately discarded as it cannot fit inside the segment as it takes up the entire capacity. In that case, I believe that your cache will fill up to 1/4th its size and only hold a single entry.

**Comment by yu199195** [comment]
@ttttangzhen @ben-manes  Hi， I'm not sure there  is bugs。

can you send email to dev@shenyu.apache.org?  We discuss with more people to get help.....

**Comment by tydhot** [comment]
@ttttangzhen https://github.com/ben-manes/caffeine/wiki/Eviction-zh-CN#基于容量 here is the Chinese wiki about caffeine's weight translated by me. Maybe it can help you.

**Comment by tuohai666** [comment]
@ben-manes Thanks for point out the problem.

**Comment by ttttangzhen** [comment]
@ben-manes @yu199195 @tydhot 
Thank you all, and I will fix this.

**Comment by kimmking** [comment]
@ben-manes Excellent description for this issue. And can you check other usage for guava library? thx.

**Comment by ben-manes** [comment]
@kimmking There are 6 identical usages that have this bug. The only other class using the cache doesn’t use a weight and looks fine.

Thanks @ttttangzhen for figuring this out.

**Comment by tydhot** [comment]
@ben-manes Thank you very much indeed! :)
