### ISSUE TITLE
plugins chain be executed twice

### ISSUE THREAD

**Issue by linsongGong** [dromara/shenyu#1491]
## Describe the bug
one http request,but the plugins chain will be executed twice

## Environment

- Soul version(s): [2.3.0]

## Steps to reproduce
1.start shenyu-admin and shenyu-bootstrap
2.start the shenyu-examples-http
3.rquest the service:eg.http://0.0.0.0:9195/http/order/findById?id=1

## Debug logs

![image](https://user-images.githubusercontent.com/27799403/118782719-f9da5880-b8c0-11eb-97ff-e3869cfbb3d3.png)

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by yu199195** [comment]
Hi,  

Did one request execute the same plugin, or was it a different request?

**Comment by linsongGong** [comment]
one request execute the same plugin

**Comment by yu199195** [comment]
> one request execute the same plugin

Ok, i will checked..

**Comment by linsongGong** [comment]
> > one request execute the same plugin
> 
> Ok, i will checked..

after WebClientResponsePlugin will app

**Comment by yu199195** [comment]
i checked,  will only be executed once

**Comment by linsongGong** [comment]
> i checked, will only be executed once

http://0.0.0.0:9195/http/order/findById?id=1  get request, use postman is normal,use chrome will be executed twice.

**Comment by MarcusJiang1306** [comment]
Because chrome will request for favicon.ico
