### ISSUE TITLE
Use SPI refactor PredicateJudge

### ISSUE THREAD

**Issue by yu199195** [dromara/shenyu#1496]
refactor `org.apache.shenyu.plugin.base.condition.judge.PredicateJudge` to ShenYu SPI

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by leven-space** [comment]
hi

I’m  interested in this feature~

**Comment by yu199195** [comment]
@leven-space 

thanks, i will assigness to you
