### ISSUE TITLE
Refactor code about "async invoke" is not supported in Dubbo lower than 2.7.3

### ISSUE THREAD

**Issue by KevinClair** [dromara/shenyu#1498]
## Feature Request
Not long ago, we found a problem that `async invoke` is not supported in Dubbo lower than 2.7.3. At that time, the problem was solved by judging the version, you can check it here #1321 . However, after our discussion, we think that the operation of judging the version is redundant, so we decided to refactor the code here. 

#### Describe the solution
* In Dubbo higher than 2.7.3, the `async invoke` is supported, but it just wrap the $invoke method with CompletableFuture.
```java
public interface GenericService {

    /**
     * Generic invocation
     *
     * @param method         Method name, e.g. findPerson. If there are overridden methods, parameter info is
     *                       required, e.g. findPerson(java.lang.String)
     * @param parameterTypes Parameter types
     * @param args           Arguments
     * @return invocation return value
     * @throws GenericException potential exception thrown from the invocation
     */
    Object $invoke(String method, String[] parameterTypes, Object[] args) throws GenericException;

    default CompletableFuture<Object> $invokeAsync(String method, String[] parameterTypes, Object[] args) throws GenericException {
        Object object = $invoke(method, parameterTypes, args);
        if (object instanceof CompletableFuture) {
            return (CompletableFuture<Object>) object;
        }
        return CompletableFuture.completedFuture(object);
    }

}
```
* If you have any thoughts and opinions, please point them out in this issues.

**Comment by dengliming** [comment]
Thanks. totally agree : )

**Comment by ttttangzhen** [comment]
Hi,@KevinClair 
I have a different opinion, I think it's necessary.

I guess you might want to replace `asyncInvoke` with `invoke`. ( If it’s not my guess, can you describe your other solutions? )
But, in Dubbo org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker#invoke
```
if (InvokeMode.SYNC == ((RpcInvocation) invocation).getInvokeMode()) {
    asyncResult.get(Integer.MAX_VALUE, TimeUnit.MILLISECONDS);
}
```

If you use `invoke`,the invokeModel will be `SYNC`, dubbo provider will block until get result.

**Comment by yu199195** [comment]
@ttttangzhen  hi

so we donot  Simple refactor  asyncInvoke  to  invoke  like this , we should  find out the specific impl inside dubbo。

```
Object object = $invoke(method, parameterTypes, args);
        if (object instanceof CompletableFuture) {
            return (CompletableFuture<Object>) object;
        }
        return CompletableFuture.completedFuture(object);
```

**Comment by ttttangzhen** [comment]
Thanks your reply, I got it!

we can use method  `invoke` and change `InvokeMode` to InvokeMode.ASYNC when we send request.

**Comment by ttttangzhen** [comment]
😁
I want to try to refactor this, can I ?

**Comment by yu199195** [comment]
@ttttangzhen   Ok， you can work on this issue..

**Comment by KevinClair** [comment]
Of course, welcome.

**Comment by dengliming** [comment]
> we can use method `invoke` and change `InvokeMode` to InvokeMode.ASYNC when we send request.

@ttttangzhen You should confirm which version introduced `InvokeMode` class before you doing this.

**Comment by ttttangzhen** [comment]
@dengliming 
Thank you for your suggestion.
 I will check this, and give a solution before development
