### ISSUE TITLE
Add MatchStrategyFactory Test

### ISSUE THREAD

**Issue by yu199195** [dromara/shenyu#1507]
## Task

add test

Task List:

- [ ] Add  MatchStrategyFactoryTest to test  MatchStrategyFactory

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by ttttangzhen** [comment]
I wanna do this, please assign me

**Comment by yu199195** [comment]
please to dev@shenyu.apache.org

**Comment by Banana1995** [comment]
I can do this task , please assign to me

**Comment by ttttangzhen** [comment]
> please to [dev@shenyu.apache.org](mailto:dev@shenyu.apache.org)

Done,  Very happy to be able to participate
