### ISSUE TITLE
Data Sync Center Support Etcd

### ISSUE THREAD

**Issue by lw1243925457** [dromara/shenyu#1545]
## Task

Data Sync Center Support consul

Task List:

- [ ] Data Sync Center Support consul

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by lw1243925457** [comment]
I want to do this, plz assign me

**Comment by plutokaito** [comment]
could i in join u, and do something ?

**Comment by lw1243925457** [comment]
oh, bro, sorry. most of them have been finished. In the final debugging verification.
