### ISSUE TITLE
Custom  AbstractSoulPlugin not work

### ISSUE THREAD

**Issue by yqwoe** [dromara/shenyu#1547]
## Describe the bug

According to the document https://dromara.org/projects/soul/custom-plugin/ "Matching Traffic Processing Plugin" does not work, request does not enter

## Environment

- Soul version(s): [e.g. 2.3.0]

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by KevinClair** [comment]
Please describe in detail.

**Comment by dengliming** [comment]
@yqwoe We need a clear and concise description of what the bug is and the steps to reproduce.
