### ISSUE TITLE
 Does Jwt plugin need path filtering

### ISSUE THREAD

**Issue by ttttangzhen** [dromara/shenyu#1548]
in Jwt plugin 
`org.apache.shenyu.plugin.jwt.JwtPlugin#doExecute`

```
@Override
    protected Mono<Void> doExecute(final ServerWebExchange exchange, final ShenyuPluginChain chain, final SelectorData selector, final RuleData rule) {
        //....
        String path = exchange.getRequest().getURI().getPath();
        List<String> filterPath = jwtConfig.getFilterPath();
        if (filterPath.contains(path)) {
            return chain.execute(exchange);
        }
        // ......
    }
```
I think there is no need to do path filtering here.
All requests that can reach this plugin require authentication

**Comment by lxl910128** [comment]
I agree, all filter about plugin should be config in `selector` or `rule`

**Comment by yu199195** [comment]
if selector and rule ，not used uri match， This is also a supplementary function~

**Comment by ttttangzhen** [comment]
Got it
@lxl910128 @yu199195 Thank you all for your reply 


> if selector and rule ，not used uri match， This is also a supplementary function~
