### ISSUE TITLE
Enhance shenyu-spring-boot-starter-plugin-request module unit test

### ISSUE THREAD

**Issue by Asxing** [dromara/shenyu#1566]
Task List:

 
- [ ] Enhance shenyu-spring-boot-starter-plugin-request module unit test，make its coverage rate is more than 80%.

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by lxl910128** [comment]
let me try

**Comment by Asxing** [comment]
please to dev@shenyu.apache.org
