### ISSUE TITLE
Soul-GateWay-Admin add selector Handler

### ISSUE THREAD

**Issue by joakapp** [dromara/shenyu#1572]
## Describe the bug
When adding selector data in soul gateway admin, the handler item can't be added. After each successful modification, there is no data for the second time.

## Environment

- Soul version(s):2.3.0
- -MySQL 8.0.23

**Comment by dengliming** [comment]
which plugin? divide?

**Comment by joakapp** [comment]
divid,
主要就在sou-gateway-admin 上操作选择器时，配置handler(处理器)时添加相关配置信息，可以保存，但是数据没有入库。再次点击查看数据就是空的.

**Comment by joakapp** [comment]
divide

**Comment by dengliming** [comment]
It automatically checks to see if the `ip+port` can be connected. and It will delete it automatically if you can't connect to it. You can turn this configuration off.

https://dromara.org/zh/projects/soul/divide-plugin/
