### ISSUE TITLE
Post request, the parameters are spliced in the URL, and after forwarding to the spring MVC project, the parameters are not accepted

### ISSUE THREAD

**Issue by xinchun123** [dromara/shenyu#1580]
The soul version is 2.3.0-release, spring cloud project
The request method is: post request

localhost:9999/api-device/device/station/web/save?name=ffffff&contact=ffff&contactMobile=ffff

@PostMapping("/save")
public ApiResponse save(DeviceStationAddRequest request) {
    return deviceStationService.create(request);
}
Picture after passing through the gateway:
![微信图片_20210604124735](https://user-images.githubusercontent.com/81403058/120747110-0f8f8500-c533-11eb-9321-d85a4968eae6.png)

No direct request via gateway:
![image](https://user-images.githubusercontent.com/81403058/120746823-8ed08900-c532-11eb-9953-ae58a8ef239f.png)

 the downstream service interface can receive the request directly. If the parameter passes through the soul gateway, it cannot be received

**Comment by xinchun123** [comment]
在WebClientPlugin插件中execute方法获取到URL path方法,如果是POST请求,只会获取到URL,如果是GET请求,会获取到URL并且url上带的参数也可以获取到,我觉得是在这一步过程中,POST请求丢失了URL上面的参数
![image](https://user-images.githubusercontent.com/81403058/120752024-86c91700-c53b-11eb-96b9-2e29dccbfee2.png)

**Comment by tydhot** [comment]
well, the urlPath is put in divide plugin.
<img width="973" alt="image" src="https://user-images.githubusercontent.com/27889201/120755329-6fd8f380-c540-11eb-8887-c2d12004dba6.png">
Maybe you can debug here to see what url is put in exchange's attribute.

**Comment by yu199195** [comment]
pls in english

**Comment by xinchun123** [comment]
Our project is spring cloud. In the buildRealURL method of SpringCloudPlugin, we only deal with the GETmethod
![image](https://user-images.githubusercontent.com/81403058/120767106-74f06f80-c54d-11eb-93b8-de0881155528.png)

**Comment by xinchun123** [comment]
> 好吧，urlPath 放在了divide 插件中。 也许您可以在此处进行调试以查看将什么 url 放入 exchange 的属性中。
> <img alt="图像" width="973" src="https://user-images.githubusercontent.com/27889201/120755329-6fd8f380-c540-11eb-8887-c2d12004dba6.png">

Please take a look at my reply

**Comment by yu199195** [comment]
spring cloud plugin  have this bug， can you fix it？

**Comment by xinchun123** [comment]
> spring cloud插件有这个bug，能修复吗？

It's easy to add  POST request to judge and check whether the URL has splicing parameters

**Comment by yu199195** [comment]
pls modify this issue title， and fix it.    thanks.

**Comment by mrcaobin** [comment]
> pls in english

装你妈b的洋鬼子
