### ISSUE TITLE
Some magic values ​​and override are not standardized

### ISSUE THREAD

**Issue by leontius** [dromara/shenyu#1582]
## Describe the bug
Some magic values ​​and override are not standardized.

## Environment

- Soul version(s): master

## Steps to reproduce
![WX20210604-152843](https://user-images.githubusercontent.com/5589032/120763556-ec240480-c549-11eb-9f24-819f7410a199.png)
![WX20210604-152825](https://user-images.githubusercontent.com/5589032/120763560-ed553180-c549-11eb-9c46-b8ac1933eb2c.png)

## Debug logs

```
replace this line with your debug logs
```
</details>

**Comment by dengliming** [comment]
@leontius PR is welcome. : )
